typography_spectrum: 0.9615734242834151
color:
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
  brandStrength: 0.042782927164807916
  lightness: 0.4146079227793962
  saturation: 0.18771336367353797
  rhythmicContrast: 0.31556717422790825
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.21774897538125515
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2a5a6f6b-23ab-4e04-b7bb-3502ee0a384b.png
name: saybucket
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dbbf21ef-45dd-469e-8635-3f07f4f66d1e.png
title: SayBucket
description: Live our your bucket list life
purpose: []
