typography_spectrum: 0.9035389630589634
color:
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  brandStrength: 0.9370901754591614
  lightness: 0.9454365684650838
  saturation: 0.4431031006388366
  rhythmicContrast: 0.35266804858110845
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8005501884035766
analytics:
  google: null
  facebook: null
  twitter: null
name: saybucket
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: SayBucket
description: Your bucketlist dreams start here
purpose: []
