typography_spectrum: 0.9615734242834151
color:
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
  brandStrength: 0.042782927164807916
  lightness: 0.4146079227793962
  saturation: 0.18771336367353797
  rhythmicContrast: 0.31556717422790825
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.21774897538125515
analytics:
  google: null
  facebook: null
  twitter: null
name: saybucket
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: SayBucket
description: Your bucketlist dreams start here
purpose: []
