typography_spectrum: 0.34655
color:
  brandColors:
    - '#4f8de2'
    - '#8ed3fc'
    - '#060d06'
    - '#7c4e00'
    - '#feff00'
  brandStrength: 0.9237657289486378
  lightness: 0.26909092883579433
  saturation: 0.9242130748461932
  rhythmicContrast: 0.5730242296122015
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.39827
analytics:
  google: null
  facebook: null
  twitter: null
name: saybucket
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: SayBucket
purpose: []
