typography_spectrum: 0.6275218306109309
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.22493257885798812
  lightness: 0.6174757978878915
  saturation: 0.904591916827485
  rhythmicContrast: 0.8697350642178208
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6673517967574298
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2a5a6f6b-23ab-4e04-b7bb-3502ee0a384b.png
name: saybucket
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Bucket list - Paragliding
    id: 9062a396-461d-4d28-bc48-ec077f8ff6fd
    type: content
  - name: Facebook Page
    url: 'https://www.facebook.com/saybucket'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dbbf21ef-45dd-469e-8635-3f07f4f66d1e.png
title: SayBucket
description: Live our your bucket list life
purpose: []
